




#pragma config(Sensor, S1,     ,               sensorEV3_Color)
#pragma config(Motor,  motorB,           ,             tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-compass.h"
int alpha = 0,  beta=0, v=100 ;
task comp()
{float u,k=3;

	tHTMC compass;
	initSensor(&compass,S2);
	sleep(200);
	readSensor(&compass);
	compass.offset=compass.heading;
	displayBigTextLine(4, "Target: %4d", compass.offset);
	wait1Msec(200);
	int err;
	alpha = beta = compass.heading;
	while (true)
	{
		readSensor(&compass);
		err=alpha-compass.heading;
		u=k*(err-err/180*360)*(1);//*-1
		motor[motorB]=v-u;
		motor[motorC]=v+u;
		wait1Msec(1);
	}
}
task main()

{int	green = SensorValue[S1];
	while(!getButtonPress(buttonUp))sleep(1);
	int	white1 = SensorValue[S1];
	while(!getButtonPress(buttonDown))sleep(1);
	int	grey1=(green+white1 )/2;
	motor[motorB] = 0;
	motor[motorC] = 0;
	wait1Msec(3000);
	tHTMC compass;
	initSensor(&compass,S2);
	sleep(2);
	readSensor(&compass);
	compass.offset=compass.heading;
	displayBigTextLine(4, "Target: %4d", compass.offset);
	wait1Msec(2);
	readSensor(&compass);
	alpha = beta;
	startTask(comp);
	while(true)
	{
		readSensor(&compass);
		for(int i=0;i<3;i++)
		{
			readSensor(&compass);
			alpha = beta;
			v=100;
			while(SensorValue[S4]>grey1-2)

			sleep(100);

			alpha=(beta+20)%360;

			v=-100;
			sleep(1650);

		}

		for(int i=0;i<3;i++)
		{
			readSensor(&compass);
			alpha = beta;
			v=100;
			while(SensorValue[S4]>grey1-2)

			sleep(100);

			alpha=(beta-20)%360;

			v=-100;
			sleep(1650);


		}
	}
}
