#pragma config(Sensor, S1,     ,               sensorEV3_Color)
#pragma config(Sensor, S2,     ,               sensorI2CCustom)
#pragma config(Sensor, S3,     ,               sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include 	"hitechnic-irseeker-v2.h"

task main ()
{
		int white1 =6;

	tHTIRS2 irSeeker;
	initSensor(&irSeeker,S3);
	float u,v=20;
	while(true)
	{
		readSensor(&irSeeker);
		int err = irSeeker.acDirection-5;
		displayBigTextLine(2,"IR=%d",irSeeker.acDirection);
		displayBigTextLine(6,"err=%d",err);
		u=err*(10);
		int mB=v-u;
		int mC=v+u;
		if(abs(mB)>100) mB=sgn(mB)*100;
		if(abs(mC)>100) mB=sgn(mC)*100;


		motor[motorB]=mB;
		motor[motorC]=mC;
		sleep(10);
	}









}
