#pragma config(Sensor, S1,     ,               sensorEV3_Color)
#pragma config(Sensor, S2,     ,               sensorEV3_GenericI2C)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-compass.h"
int alpha = 0,  beta=0, v=50;
task comp()
{float u,k=3;

	tHTMC compass;
	initSensor(&compass,S2);
	sleep(200);
	readSensor(&compass);
	compass.offset=compass.heading;
	displayBigTextLine(4, "Target: %4d", compass.offset);
	wait1Msec(200);
	int err;
	alpha = beta = compass.heading;
	while (true)
	{

		readSensor(&compass);
		err=alpha-compass.heading;
		u=k*(err-err/180*360);
		motor[motorB]=v+u;
		motor[motorC]=v-u;
		wait1Msec(1);
	}
}
task main()

{int	black1 = SensorValue[S1];
	while(!getButtonPress(buttonUp))Sleep(1);
	int	white1 = SensorValue[S1];
	while(!getButtonPress(buttonRight))Sleep(1);
	int	grey1=(black1+white1 )/2;
	motor[motorB] = 0;
	motor[motorC] = 0;
	wait1Msec(3000);

	startTask(comp);
	for(int i=0;i<10;i++)
	{

		alpha = beta;
		v=100;
		while(SensorValue[S1]>grey1)

		sleep(1);

		alpha=(beta+5)%360;
		v=-50;
		sleep(4000);

	}
}
