#pragma config(Sensor, S1,     Color,          sensorEV3_Color)
#pragma config(Sensor, S2,     Gyro,           sensorEV3_Gyro)
#pragma config(Sensor, S3,     Touch,          sensorEV3_Touch)
#pragma config(Sensor, S4,     Ultrasonic,     sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          B,             tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorC,          C,             tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	displayBigTextLine(4,"%d",SensorValue[Ultrasonic]);
   sleep(100000);

   displayBigTextLine(6,"%d",SensorValue[Gyro]);
   sleep(100000);

   	displayBigTextLine(8,"%d",SensorValue[Touch]);
   sleep(100000);

   	displayBigTextLine(2,"%d",SensorValue[Color]);
   sleep(100000);




}
