
#pragma config(Sensor, S1,     ,               sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     ,              sensorI2CCustom)
#pragma config(Sensor, S3,     HTIRS2,         sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-irseeker-v2.h"
#include "hitechnic-compass.h"

task main ()
{
	float u, v=40,V=-30, err, ks=0.2,e=0;
	wait1Msec(100);
	tHTMC compass;
	initSensor(&compass, S2);
	sleep(200);
	readSensor(&compass);
	compass.offset = compass.heading;
	int alpha=compass.heading;
	tHTIRS2 irSeeker;
	initSensor(&irSeeker, S3);


	motor[motorB] = 0;
	motor[motorC] = 0;
	while(!getButtonPress(buttonEnter))sleep(1);
	wait1Msec(1000);


	while(true)
	{

		readSensor(&irSeeker);
		if (SensorValue[S1]>3)
			//	if (irSeeker.acValues[2]>160)
		//readSensor(Compass)
		{                          //forward boost;
			//get back across black line;
			//repeat;
			e=alpha-compass.heading;
			e=e-(e/180)*360;
			int sector=5+ks*e/30.0;
			err=sector-irSeeker.acDirection;
			u=-err*10;

			int mB=v-u;
			int mC=v+u;
			if (abs(mB)>100) mB=sgn(mB)*100;
			if (abs(mC)>100) mC=sgn(mC)*100;
			motor[motorB]=mB;
			motor[motorC]=mC;
			sleep(10);

			//	motor[motorB]=13;
			//	motor[motorC]=12;
		}

		else

		{//get back & look after ball;
			while(nMotorEncoder[motorB]>-120){
				readSensor(&compass);
				int k=3;
				err=alpha-compass.heading;
				u=k*(err-err/180*360)*(1);//*-1
				motor[motorB]=V-u;
				motor[motorC]=V+u;
				wait1Msec(1);
			}
		}


	}

}
//}
