#pragma config(Sensor, S1,     ,               sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{float k=1.5, grey1, grey2,v=30;
	int	black1 = SensorValue[S1];
	int	black2 = SensorValue[S2];
	while(!getButtonPress(buttonUp))sleep(1);
	int	white1 = SensorValue[S1];
	int	white2 = SensorValue[S2];
	while(!getButtonPress(buttonRight))sleep(1);
	grey1=(black1+white1 )/2;
	grey2=(black2+white2 )/2;
	motor[motorB] = 0;
	motor[motorC] = 0;
	wait1Msec(3000);
	while(true)

	{


		int	u=k*(SensorValue[S1]-grey1);
		motor[motorB]=v+u;
		motor[motorC]=v-u;
		wait1Msec(1);

	}


}
