//just some balancing robot
//JSBr

#pragma config(Sensor, S1,     ,               sensorEV3_Color)
#pragma config(Sensor, S2,     ,               sensorEV3_Gyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{

sleep(100);resetGyro(S2);sleep(100);
while(true)
{
displayBigTextLine(1,"gyro rate=%d",getGyroRate(S2));
displayBigTextLine(3,"gyro degr=%d",getGyroDegrees(S2));
sleep(1);
}

}
