#pragma config(Sensor, S1,     ,               sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	int v, k=3 ;
	nMotorEncoder[motorA]=0;
	int alpha=0;
	while(true)
	{if(SensorValue[S1]>100)
		{alpha=100;
			v=75;
		}
		else
		{alpha=SensorValue[S1];
			v=100-abs(50-SensorValue[S1])/2;
		}
		motor[motorA]=k*(alpha-nMotorEncoder[motorA]);
		motor[motorB]=-v;
		sleep(1);
	}
}
