#pragma config(Sensor, S1,     ,               sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S2,     ,               sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S3,     ,               sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void move1()
{	nMotorEncoder[motorB] = 0;
	motor[motorB] = 50;
	motor[motorC] = -50;
	while(nMotorEncoder[motorB]<140);//right//
		wait1Msec(100);

	nMotorEncoder[motorB] = 0;
	motor[motorB] = 50;
	motor[motorC] = 50;
	while(nMotorEncoder[motorB]<200);//forward//
		wait1Msec(100);

	nMotorEncoder[motorB] = 0;
	motor[motorB] = -50;
	motor[motorC] = 50;
	while(nMotorEncoder[motorB]>-117);//left//
		wait1Msec(100);

	nMotorEncoder[motorB] = 0;
	motor[motorB] = 50;
	motor[motorC] = 50;
	while(nMotorEncoder[motorB]<750);//forward//
		wait1Msec(100);

	nMotorEncoder[motorB] = 0;
	motor[motorB] = -50;
	motor[motorC] = 50;
	while(nMotorEncoder[motorB]>-117);//left//
		wait1Msec(100);

	nMotorEncoder[motorB] = 0;
	motor[motorB] = 50;
	motor[motorC] = 50;
	while(nMotorEncoder[motorB]<210);//forward//
		wait1Msec(100);

	nMotorEncoder[motorB] = 0;
	motor[motorB] = 50;
	motor[motorC] = -50;
	while(nMotorEncoder[motorB]<155);//right//
		wait1Msec(100);
}
task main()
{float u,v,es,eold,e,k1=5.4,k2=9.6;

	es = SensorValue[S1]-SensorValue[S2];
	eold = 0;
	while(true)
	{


		displayBigTextLine(4,"%d",u);

		if(SensorValue[S3]>6)
		{
			e = SensorValue[S1]-SensorValue[S2]-es;
			u = k1*e+k2*(e-eold);
			eold = e;
			v = 30-abs(u)*0.001;
			motor[motorB] = v+u;
			motor[motorC] = v-u;
			wait1Msec(1);
		}
		else
		{
			motor[motorB] = 0;
			motor[motorC] = 0;
			wait1Msec(100);

			move1();

		}


	}


}
