#pragma config(Sensor, S1,     ,               sensorEV3_Color)
#pragma config(Sensor, S2,     ,               sensorEV3_Color)
#pragma config(Sensor, S3,     ,               sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void move1()
{	nMotorEncoder[motorB] = 0;
	motor[motorB] = 50;
	motor[motorC] = -50;
	while(nMotorEncoder[motorB]<140);//right//
		wait1Msec(100);

	nMotorEncoder[motorB] = 0;
	motor[motorB] = 50;
	motor[motorC] = 50;
	while(nMotorEncoder[motorB]<200);//forward//
		wait1Msec(100);

	nMotorEncoder[motorB] = 0;
	motor[motorB] = -50;
	motor[motorC] = 50;
	while(nMotorEncoder[motorB]>-117);//left//
		wait1Msec(100);

	nMotorEncoder[motorB] = 0;
	motor[motorB] = 50;
	motor[motorC] = 50;
	while(nMotorEncoder[motorB]<750);//forward//
		wait1Msec(100);

	nMotorEncoder[motorB] = 0;
	motor[motorB] = -50;
	motor[motorC] = 50;
	while(nMotorEncoder[motorB]>-117);//left//
		wait1Msec(100);

	nMotorEncoder[motorB] = 0;
	motor[motorB] = 50;
	motor[motorC] = 50;
	while(nMotorEncoder[motorB]<210);//forward//
		wait1Msec(100);

	nMotorEncoder[motorB] = 0;
	motor[motorB] = 50;
	motor[motorC] = -50;
	while(nMotorEncoder[motorB]<155);//right//
		wait1Msec(100);
}
task main()
{float u,v,es,eold,e,k1 = 6.4,k2 = 10.6,kv = 1,t2 = 0,kp;
int	speed2 = 120;
	es = SensorValue[S1]-SensorValue[S2];
	eold = 0;
	while(true)
	{displayBigTextLine(2,"%d",u);
		displayBigTextLine(4,"%d",motor[motorB]);
		displayBigTextLine(6,"%d",motor[motorC]);

		if(SensorValue[S3]>6)
		{
			e = SensorValue[S1]-SensorValue[S2]-es;
			u = k1*e+k2*(e-eold);
			eold = e;

			v = 30-abs(u)*0.001;
			motor[motorB] = v+u;
			motor[motorC] = v-u;
			wait1Msec(1);

			nMotorEncoder[motorB] = 0;
			nMotorEncoder[motorC] = 0;
		while((motor[motorB]>=25)&&(motor[motorC]>=25))
			{int enc = nMotorEncoder[motorB] + nMotorEncoder[motorC] / 2;
				int err = time1[T2] * 0.001 * speed2 - enc ;
				v = err * kv;
				kp = 1 + v/10;
				while(t2<50000)
			{

				motor[motorB] = - v + u;
				motor[motorC] = - v + u;
				sleep(1);

			}
			t2=time1(T2);
			}
	{


}
		}
		else
		{
			motor[motorB] = 0;
			motor[motorC] = 0;
			wait1Msec(100);

			move1();

		}


	}


}
