#pragma config(Sensor, S1,     ,               sensorEV3_Color, modeEV3Color_Reflected_Raw)
#pragma config(Sensor, S2,     ,               sensorEV3_Color, modeEV3Color_Reflected_Raw)
#pragma config(Sensor, S3,     ,               sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void move1()
{
	nMotorEncoder[motorB] = 0;
	motor[motorB] = 50;
	motor[motorC] = -50;
	while(nMotorEncoder[motorB]<180);//left//
		motor[motorB]=motor[motorC]=0;
		wait1Msec(5000);

	if (SensorValue[S3]>10)
	{

		nMotorEncoder[motorB] = 0;
		motor[motorB] = motor[motorC] =  50;

		while(nMotorEncoder[motorB]<250);//forward//
			wait1Msec(100);

		nMotorEncoder[motorB] = 0;
		motor[motorB] = -50;
		motor[motorC] = 50;
		while(nMotorEncoder[motorB]>-97);//right//
			wait1Msec(100);

		nMotorEncoder[motorB] = 0;
		motor[motorB] = motor[motorC] = 50;

		while(nMotorEncoder[motorB]<770);//forward//
			wait1Msec(100);

		nMotorEncoder[motorB] = 0;
		motor[motorB] = -50;
		motor[motorC] = 50;
		while(nMotorEncoder[motorB]>-87);//right//
			wait1Msec(100);

		nMotorEncoder[motorB] = 0;
		motor[motorB] =  motor[motorC] = 50;

		while(nMotorEncoder[motorB]<430);//forward//
			wait1Msec(100);

		nMotorEncoder[motorB] = 0;
		motor[motorB] = 50;
		motor[motorC] = -50;
		while(nMotorEncoder[motorB]<235);//left//

		wait1Msec(100);
	}
	else
	{//Right manuevor

		nMotorEncoder[motorB] = 0;
		motor[motorB] = -50;
		motor[motorC] = 50;
		while(nMotorEncoder[motorB]>-360);//right//
			wait1Msec(100);

			nMotorEncoder[motorB] = 0;
		motor[motorB] = motor[motorC] = 50;

		while(nMotorEncoder[motorB]<250);//forward//
			wait1Msec(100);

			nMotorEncoder[motorB] = 0;
		motor[motorB] = 50;
		motor[motorC] = -50;
		while(nMotorEncoder[motorB]<175);//left//


		nMotorEncoder[motorB] = 0;
		motor[motorB] = motor[motorC] = 50;

		while(nMotorEncoder[motorB]<770);//forward//
			wait1Msec(100);

			nMotorEncoder[motorB] = 0;
		motor[motorB] = 50;
		motor[motorC] = -50;
		while(nMotorEncoder[motorB]<155);//left//

		nMotorEncoder[motorB] = 0;
		motor[motorB] = motor[motorC] = 50;

		while(nMotorEncoder[motorB]<430);//forward//
			wait1Msec(100);

			nMotorEncoder[motorB] = 0;
		motor[motorB] = -50;
		motor[motorC] = 50;
		while(nMotorEncoder[motorB]>-180);//right//
			wait1Msec(100);


	}
}
task main()
{float u,v,es,eold,e,k1=2.1,k2=3.6;
	es = SensorValue[S1]-SensorValue[S2];
	eold = 0;
	while(true)
	{displayBigTextLine(4,"%d",u);

		if(SensorValue[S3]>6)
		{
			e = SensorValue[S1]-SensorValue[S2]-es;
			u = k1*e+k2*(e-eold);
			eold = e;
			v = 30-abs(u)*0.1;
			motor[motorB] = v+u;
			motor[motorC] = v-u;
			wait1Msec(1);
		}
		else
		{
			motor[motorB] = 0;
			motor[motorC] = 0;
			wait1Msec(100);

			move1();

		}


	}


}
