#pragma config(Sensor, S1,     ,               sensorLightActive)
#pragma config(Sensor, S2,     ,               sensorLightActive)
#pragma config(Motor,  motorB,           ,             tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{float u,v,es,eold,e,k1=2.4,k2=2.9,count =0;
	int	black1 = SensorValue[S1];
	int	black2 = SensorValue[S2];
	while(!getButtonPress(buttonUp))sleep(1);
	int	white1 = SensorValue[S1];
	int	white2 = SensorValue[S2];
	while(!getButtonPress(buttonRight))sleep(1);
	int	grey1=(black1+white1 )/2;
	int	grey2=(black2+white2 )/2;
	motor[motorB] = 0;
	motor[motorC] = 0;
	wait1Msec(3000);
	es = SensorValue[S1]-SensorValue[S2];
	eold = 0;
	clearTimer(T1);
	while(count<1)
	{
		if(SensorValue[S1]<grey1 && SensorValue[S2]<grey2 &&time1[T1]>120)
		{count++;
			playSound(soundBlip);
			clearTimer(T1);

		}
		e = SensorValue[S1]-SensorValue[S2]-es;
		u = k1*e+k2*(e-eold);
		eold = e;
		v = 60-abs(u)*0.01;
		motor[motorB] = v+u;
		motor[motorC] = v-u;
		wait1Msec(1);


	}
nMotorEncoder[motorB] = 0;
	motor[motorB] = 50;
	motor[motorC] = -50;
	while(nMotorEncoder[motorB]<151);//left//
		motor[motorB]=70;
	motor[motorC]=70;
	while(nMotorEncoder[motorB]<1000);//out of box
		wait1Msec(100);


}
