#pragma config(Sensor, S1,     ,               sensorEV3_Color)
#pragma config(Sensor, S2,     ,               sensorEV3_Color)
#pragma config(Sensor, S3,     ,               sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,           ,             tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void move1()
{ int n = 1;
	if (n==-1)
	{		nMotorEncoder[motorB] = 0;
		motor[motorB] = 50;
		motor[motorC] = -50;
		while(nMotorEncoder[motorB]<230);//left//
			motor[motorB]=motor[motorC]=0;
		wait1Msec(500);



		nMotorEncoder[motorB] = 0;
		motor[motorB] = 30;
		motor[motorC] = 57;
		while(nMotorEncoder[motorB]<350);
		nMotorEncoder[motorB] = 0;
		motor[motorB] = 30;
		motor[motorC] = 49;
		while(nMotorEncoder[motorB]<420);

		nMotorEncoder[motorB] = 0;
		motor[motorB] = 50;
		motor[motorC] = -50;
		while(nMotorEncoder[motorB]<335);//left//

		wait1Msec(100);
		n=n*-1;
	}
	else
	{//Right manuevor

		nMotorEncoder[motorB] = 0;
		motor[motorB] = -50;
		motor[motorC] = 50;
		while(nMotorEncoder[motorB]>-270);//right//
			wait1Msec(100);

		nMotorEncoder[motorB] = 0;
		motor[motorB] = 57;
		motor[motorC] = 30;
		while(nMotorEncoder[motorB]<230);//right//
			wait1Msec(100);



		nMotorEncoder[motorB] = 0;
		motor[motorB] = -50;
		motor[motorC] = 50;
		while(nMotorEncoder[motorB]>-270);//right//
			wait1Msec(100);
		n=n*-1;

	}
}
task main()
{float u,v,es,eold,e,k1=3.2,k2=9,n=1;
	es = SensorValue[S1]-SensorValue[S2];
	eold = 0;
	if(SensorValue[S3]>5)
	{
		e = SensorValue[S1]-SensorValue[S2]-es;
		u = k1*e+k2*(e-eold);
		eold = e;
		v = 74-abs(u)*0.2;
		motor[motorB] = v+u;
		motor[motorC] = v-u;
		wait1Msec(1);

	}
	else
	{
		motor[motorB] = 0;
		motor[motorC] = 0;
		wait1Msec(100);
		move1();

	}

}
