#pragma config(Sensor, S4,     Ultrasonic,     sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{while(true)
 {

 motor[motorB]=100;
 motor[motorC]=100;
 while(SensorValue[Ultrasonic]>30)
   sleep(1);
 motor[motorB]=-50;
 motor[motorC]=-10;
 nMotorEncoder[motorB]=0;
 while(nMotorEncoder[motorB]>-400)
   sleep(1);
}




}
