#pragma config(Sensor, S1,     Color,          sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	displayBigTextLine(6,"%d",SensorValue[Color]);
   sleep(100000);




}
