#pragma config(Sensor, S1,     ,               sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     ,               sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     ,               sensorEV3_Gyro)
#pragma config(Motor,  motorB,           ,             tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int angle = 0;
int V1=30;

void reset ()
{
	resetGyro(S3);
	angle=SensorValue[S3];
}
void r_gyro()
{
	motor[motorB]=15;
	motor[motorC]=-15;
	angle=angle+90;
	while (SensorValue[S3]<angle)
		sleep(1);
	motor[motorB]=motor[motorC]=0;wait10Msec(100);

}

void l_gyro()
{
	motor[motorB]=-15;
	motor[motorC]=15;
	angle=angle-90;
	while (SensorValue[S3]>angle)
		sleep(1);
	motor[motorB]=motor[motorC]=0;wait10Msec(100);

}
void Sync_forward()
{
	int v=-50,k=2,u;
	nMotorEncoder[motorB]=0;
	nMotorEncoder[motorC]=0;
	while (nMotorEncoder[motorB]>-620)
	{
		int e2=nMotorEncoder[motorB];
		int e3=nMotorEncoder[motorC];
		u=k*(e3-e2);
		motor[motorB]=v+u;
		motor[motorC]=v-u;
		wait1Msec(1);
	}
}


task main()
{

	resetGyro(S3);
	sleep(200);
	angle=SensorValue[S3];


	while(true)
	{
		if(SensorValue[S2]>15)
		{r_gyro();reset();Sync_forward();}
		else
		{
			if(SensorValue[S1]>15)
			{Sync_forward();}
			else
			{l_gyro();reset();}
		}
	}
}
