#pragma config(Sensor, S1,     ,               sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     ,               sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     ,               sensorEV3_Gyro)
#pragma config(Sensor, S4,     ,               sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorB,           ,             tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
float wk=0.5,W=40;
int angle = 0;
float V1=30, green=3, mas[100], len=0,alpha=85.6,beta=-85.6 ;
int fd=1;

void l_gyro()
{int oldangle;int p=0.5,po=20;
	resetGyro(S3);
	sleep(100);
int n=1;
	angle=SensorValue[S3];oldangle=SensorValue[S3];
	angle=angle+beta;
	while (SensorValue[S3]>angle)
	{if (SensorValue[S3]<angle*0.8&&n==1)
	{n=n*(-1);W=W/2;}

		motor[motorB]=-W*wk;
		motor[motorC]=W*wk;
	}//wk=(angle-abs(oldangle))*p+po;
	//while (SensorValue[S3]>angle)
	//	sleep(1);
	//motor[motorB]=motor[motorC]=0;wait1Msec(100);
	//	correction();
	//if(fd) mas[len++]=3;

}
task main()
{
l_gyro():


}
