#pragma config(Sensor, S4,     ,               sensorEV3_Color, modeEV3Color_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

while(true)
{int color=SensorValue[S4];displayBigTextLine(2,"Colorraw=%d",color);sleep(1);}

}
