#pragma config(Sensor, S1,     ,               sensorEV3_Color)
#pragma config(Sensor, S2,     ,               sensorEV3_GenericI2C)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-compass.h"
int alpha = 0, v=50;
task comp()
{float u,k=1.5;

	tHTMC compass;
	initSensor(&compass,S2);
	sleep(200);
	readSensor(&compass);
	compass.offset=compass.heading;
	displayBigTextLine(4, "Target: %4d", compass.offset);

	int err;
	alpha=compass.heading;
	while (true)
	{

		readSensor(&compass);
		displayBigTextLine(6, "Abs: %4d", compass.heading);
		displayBigTextLine(8, "Rel: %4d", compass.relativeHeading);


		err=alpha-compass.heading;
		u=k*(err-err/180*360);
		motor[motorB]=v+u;
		motor[motorC]=v-u;
		wait1Msec(1);
	}
}
task main()
{
	startTask(comp);
	for(int i=0;i<=8;i++)
	{
		sleep(2000);
		alpha=(alpha+150)%360;


	}
}
