#pragma config(Sensor, S3,     HTIRS2,         sensorEV3_GenericI2C)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include 	"hitechnic-irseeker-v2.h"
task main ()
{
	tHTIRS2 irSeeker;
	initSensor(&irSeeker,S3);

	while(true)
	{
		readSensor(&irSeeker);
		int err = irSeeker.acDirection-5;
		displayTextLine(2,"IR=%d",irSeeker.acDirection);
		displayTextLine(6,"err=%d",err);
		sleep(100);


	}
}
