#pragma config(Sensor, S3,     HTIRS2,         sensorEV3_GenericI2C)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-compass.h"
#include 	"hitechnic-irseeker-v2.h"
int alpha=0;
task main ()
{
	tHTMC compass;
	initSensor(&compass,S3);
	sleep(200);
	readSensor(&compass);
	compass.offset=compass.heading;
	tHTIRS2 irSeeker;
	initSensor(&irSeeker,S2);
	float u,v=50;
	int err;
	alpha=compass.heading;
	while(true)
	{ readSensor(&irSeeker);
		if 	(irSeeker.acValues[2]>200)
		{
			readSensor(&compass);
			displayTextLine(2,"IR=%d",irSeeker.acDirection);
			displayTextLine(6,"err=%d",err);
			err=alpha-compass.heading;
			u=0.5*err;



		}
		else
		{
			err=irSeeker.acDirection-5;
			u=14*err;

		}
	/*	int mB=v+u;
		int mC=v-u;
		if(abs(mB)>100) mB=sgn(mB)*100;
		if(abs(mC)>100) mB=sgn(mC)*100;
		*/
		motor[motorB]=v+u;
		motor[motorC]=v-u;
		sleep(10);
	}
}
