#pragma config(Sensor, S2,     ,               sensorI2CCustom)
#pragma config(Sensor, S3,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S4,     ,               sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorB,           ,             tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-irseeker-v2.h"
#include "hitechnic-compass.h"
task comp()
{float u,k=3,v=70;
	int beta;
	tHTMC compass;
	initSensor(&compass,S2);
	sleep(200);
	readSensor(&compass);
	compass.offset=compass.heading;
	displayBigTextLine(4, "Target: %4d", compass.offset);
	wait1Msec(200);
	int err;
	int alpha = beta = compass.heading;
	while (true)
	{
		readSensor(&compass);
		err=alpha-compass.heading;
		u=k*(err-err/180*360)*(-1);
		motor[motorB]=v-u;
		motor[motorC]=v+u;
		wait1Msec(1);
	}
}
task main ()
{
	float u, v=55, err, ks=0.2,e=0;
	wait1Msec(100);
	tHTMC compass;
	initSensor(&compass, S2);
	sleep(200);
	readSensor(&compass);
	compass.offset = compass.heading;
	int alpha=compass.heading;
	tHTIRS2 irSeeker;
	initSensor(&irSeeker, S3);

	motor[motorB] = 0;
	motor[motorC] = 0;
	while(!getButtonPress(buttonEnter))sleep(1);
	wait1Msec(1000);


	while(true)
	{


		if (SensorValue[S4]>1)//	if (irSeeker.acValues[2]>160)
			//readSensor(Compass)
		{                          //forward boost;
			motor[motorB] = 63;
			motor[motorC] = 67;

		}

		else

		{//get back & look after ball;
			motor[motorB]=motor[motorC]=0;
			wait1Msec(5);

			nMotorEncoder[motorB] = 0;
			motor[motorB] = -67;
			motor[motorC] = -67;
			while(nMotorEncoder[motorB]>-211);
		}


	}


}


//}
