#pragma config(Sensor, S4,     Ultrasonic,     sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{      while(true)
	  	{
	  		 motor[motorB]=100;
	  		 motor[motorc]=100;
	  		 while(SensorValue[Ultrasonic]>50)
	  		   sleep(1);
	  		 motor[motorB]=-50;
	  		 motor[motorC]=1;
	  		 nMotorEncoder[motorB]=0;
	  		 while(nMotorEncoder[motorB]>-400)
	  		   sleep(1);

	  		 }



}
