//just some balancing robot
//JSBr

#pragma config(Sensor, S1,     ,               sensorEV3_Color)
#pragma config(Sensor, S2,     ,               sensorEV3_Gyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{


	sleep(100);resetGyro(S2);sleep(100);
	int angVel=0;
	int gyroOffset,gyroRate,GyroRateOld=0;
	/////
	for(int i=0; i<10;i++)
	{
gyroRate=getgyroRate(S2);
if(gyroRate!=GyroRateOld) i=0;
GyroRateOld=gyroRate;
sleep(15);
displayBigTextLine(1,"gyro rate=%d",getGyroRate(S2));
}
gyroOffset=gyroRate;
displaybigTextLine(5,"gyroOffset=%d",gyroOffset);

	while(true)
	{
		angVel=gyroRate-gyroOffset;
		displayBigTextLine(7,"angVel=%d",angVel);
		//displayBigTextLine(3,"gyro degr=%d",getGyroDegrees(S2));
		sleep(1);
	}

}
