#pragma config(Sensor, S1,     ,               sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     ,               sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
int alpha=0;
int v=100;
int k=3;
int e;
while(true)
{
	e=SensorValue[S1]-SensorValue[S2];
	if (abs(e)>100)
		alpha=50+sgn(e)*50;
else
	alpha=50+e/2;
motor[motorA]=k*(alpha-nMotorEncoder[motorA]);
motor[motorB]=v;
sleep(1);
}






}
