#pragma config(Sensor, S1,     ,               sensorEV3_Color)
#pragma config(Sensor, S2,     ,               sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     ,               sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int alpha=0;
	int v=-100;
	int k=4;
	int e;
	int a;
	int w=50;
	int da=3;
	int count=0;
	float grey3=9;
	int s=40;
	motor[motorA]=-15;
	sleep(500);
	motor[motorA]=0;
	nMotorEncoder[motorA]=0;

	while(SensorValue[S2]>15)
		sleep(1);
	clearTimer(T1);

	while(count<4)
	{
		if(SensorValue[S1]<grey3 &&time1[T1]>250)
		{count++;
			playSound(soundBlip);
			clearTimer(T1);

		}

		e=SensorValue[S2]-SensorValue[S3];
		if (abs(e)>w)//...>100
			alpha=s+sgn(e)*50;//alpha = 50+...
		else
			alpha=s+e/2;
		a=a+sgn(alpha-a)*da;
		motor[motorA]=k*(a-nMotorEncoder[motorA]);
		motor[motorB]=-v;
		sleep(1);

	}


	clearTimer(T1);
	nMotorEncoder[motorB]=0;
	while(nMotorEncoder[motorB]<6000)
	{


		e=SensorValue[S2]-SensorValue[S3];
		if (abs(e)>w)//...>100
			alpha=s+sgn(e)*50;//alpha = 50+...
		else
			alpha=s+e/2;
		a=a+sgn(alpha-a)*da;
		motor[motorA]=k*(a-nMotorEncoder[motorA]);
		motor[motorB]=-v;
		sleep(1);

	}

	while(count<12)
	{
		if(SensorValue[S1]<grey3 &&time1[T1]>250)
		{count++;
			playSound(soundBlip);
			clearTimer(T1);

		}

		e=SensorValue[S2]-SensorValue[S3];
		if (abs(e)>w)//...>100
			alpha=s+sgn(e)*50;//alpha = 50+...
		else
			alpha=s+e/2;
		a=a+sgn(alpha-a)*da;
		motor[motorA]=k*(a-nMotorEncoder[motorA]);
		motor[motorB]=-v;
		sleep(1);

	}
	motor[motorA]=0;
	motor[motorB]=0;
	wait1Msec(2000);
	while(true)
	{

		e=SensorValue[S2]-SensorValue[S3];
		if (abs(e)>w)//...>100
			alpha=s+sgn(e)*50;//alpha = 50+...
		else
			alpha=s+e/2;
		a=a+sgn(alpha-a)*da;
		motor[motorA]=k*(a-nMotorEncoder[motorA]);
		motor[motorB]=-v;
		sleep(1);

	}

}
