#pragma config(Sensor, S1,     ,               sensorEV3_Color)
#pragma config(Sensor, S2,     ,               sensorEV3_Gyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int  gyroRate ,dT=10;
float angle=0;
task displayShow()
{
	while (true)
	{

		displayBigTextLine(1,"GyroR %d", gyroRate);
		displayBigTextLine(3,"angle %f", angle);
		sleep(dT);
	}
}
task main()
{
	//startTask(displayShow);
float k=3,k2=30,u;


while(true)
{
	gyroRate=getGyroRate(S2);angle=angle+gyroRate*(dT*0.001);
 u= gyroRate*k+angle*k2;
	motor[motorB]=-u;
	motor[motorC]=-u;
}





}
