#pragma config(Sensor, S3,     ,               sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-compass.h"
#include 	"hitechnic-irseeker-v2.h"
int alpha=0,beta=0,ek;
task comp ()
{

	tHTMC compass;
	initSensor(&compass,S4);
	sleep(200);
	readSensor(&compass);
	compass.offset=compass.heading;
	tHTIRS2 irSeeker;
	initSensor(&irSeeker,S1);
	int e= alpha-compass.heading;
	ek=e-(e/180)*360;

	while (true)
	{	float u,v=40,ks=0.2,kir,kirmin=8,kr=0.5;
		int err;
		readSensor(&irSeeker);
		motor[motorB]=v+u;
		motor[motorC]=v-u;
		sleep(1);
	}
}
task main ()
{
	tHTMC compass;
	initSensor(&compass,S4);
	sleep(200);

	startTask  (comp);
	readSensor(&compass);
	compass.offset=compass.heading;
	tHTIRS2 irSeeker;
	initSensor(&irSeeker,S1);
	float u,v=30,kr=0.5;
	int beta=alpha;

	int err;
	alpha=compass.heading;
	while(true)
	{ readSensor(&irSeeker);
		alpha=beta;sleep(50);
		if(abs(ek)<30)
		{
			if(SensorValue[S2]>60)
		{alpha=beta+30;
			sleep(150);}
		else
		{if(SensorValue[S2]<40)
			{alpha =beta-30;
				sleep(150);
			}
			if 	(irSeeker.acValues[2]>70)
			{	readSensor(&compass);

				displayTextLine(2,"IR=%d",irSeeker.acDirection);
				displayTextLine(6,"err=%d",err);
				int e=irSeeker.acDirection-5;
				int beta = alpha+kr*e*30;
				err=beta-compass.heading;

				err=err-(err/180)*360;


				u=err*1.1*(-1);
				/*
				readSensor(&compass);
				displayTextLine(2,"IR=%d",irSeeker.acDirection);
				displayTextLine(6,"err=%d",err);
				err=alpha-compass.heading;
				u=0.3*err*(-1);
				*/


			}
			else
			{
				err=irSeeker.acDirection-5;
				u=37*err;

			}

			/*		int mB=v+u;
			int mC=v-u;
			if(abs(mB)>100) mB=sgn(mB)*20;
			if(abs(mC)>100) mB=sgn(mC)*20;
			motor[motorB]=mB;
			motor[motorC]=mC;
			*/
			motor[motorB]=v+u;

			motor[motorC]=v-u;
			sleep(10);
		}
	}
}
}
